name: 'trivy-reporter-action'
description: 'A GitHub Action to manage Trivy security reports using GitHub Issues'
author: 'Bruno Paz'

branding:
  icon: shield
  color: blue

inputs:
  report-path:
    description: 'The path to the Trivy report file in JSON format'
    required: false
    default: 'trivy-report.json'
  issue-title:
    description: 'The title of the GitHub Issue to create or update'
    required: false
    default: 'Trivy Security Report'
  github-token:
    description: 'GitHub token to authenticate API requests'
    required: true
  labels:
    description: 'Comma-separated list of labels to apply to the issue'
    required: false
    default: ''
  issue-mode:
    description: "Issue creation mode: 'single' for one consolidated report, 'per-cve' for separate issues per vulnerability"
    required: false
    default: 'single'

outputs:
  issue-url:
    description: 'The URL of the created or updated GitHub Issue containing the Trivy report'

runs:
  using: node24
  main: ./dist/index.mjs
